### ISSUE TITLE
感谢Roc，期待开源

### ISSUE THREAD

**Issue by zhoushiya** [rocboss/paopao-ce#1]

**Comment by iddhub** [comment]
加油！

**Comment by zhoushiya** [comment]
实在是不好意思roc,本来想宣传一下的，是我低估了V2EX，那里真是一个卧龙凤雏遍布的地方，呵呵

**Comment by rocboss** [comment]
> 



> 实在是不好意思roc,本来想宣传一下的，是我低估了V2EX，那里真是一个卧龙凤雏遍布的地方，呵呵

没关系习惯了，做好自己就行，别浪费时间在上面争吵，没意义

PaoPao近期会找个时间整理下开源，不管几个star，本意只是提高下门槛而已
