### ISSUE TITLE
关于搜索接口报错，请教下是不是Zinc配置的问题

### ISSUE THREAD

**Issue by 120nft** [rocboss/paopao-ce#110]
测试站点：du.hawazi.com
请求接口：https://cdn.hawazi.com/v1/posts?query=打包&page=1&page_size=20
报错：{code: 30001, msg: "获取动态列表失败"}

config.yaml配置
Zinc: # Zinc搜索配置
  Host: 110.40.139.219:4080
  Index: paopao-data
  User: admin
  Password: admin

**Comment by 120nft** [comment]
docker run -d  -v /root/data:/data -e DATA_PATH="/data" -p 4080:4080 -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=admin --name zinc public.ecr.aws/h9e2j3o7/zinc:latest
直接运行后查看了进程，没啥问题吧 
[root@VM-4-17-centos ~]# docker ps -a 
CONTAINER ID   IMAGE                                 COMMAND          CREATED         STATUS         PORTS                                       NAMES
89cc88d1f0ed   public.ecr.aws/h9e2j3o7/zinc:latest   "/go/bin/zinc"   4 minutes ago   Up 4 minutes   0.0.0.0:4080->4080/tcp, :::4080->4080/tcp   zinc

**Comment by alimy** [comment]
```
Zinc: # Zinc搜索配置
  Host: http://127.0.0.1:4080
  Index: paopao-data
  User: admin
  Password: admin
```
Host需要 http或https打头 `Host: http://127.0.0.1:4080`

**Comment by alimy** [comment]
这里应该叫Domain比较合适， Host有点不对味，后面搜索这块可能还会有优化，配置这块应该会有所改动。

**Comment by 120nft** [comment]
Zinc 用docker有点麻烦啊 这个https-http问题试了好多方法都不行，求支招啊！！！
附报错信息：
{"level":"error","msg":"service.GetPostListFromSearch err: Post \"https://110.40.139.219:4080/api/paopao-data/_search\": http: server gave HTTP response to HTTPS client\n","time":"2022-06-18T00:40:04+08:00"}

**Comment by 120nft** [comment]
如果config.yaml 配置中host的换成http就直接报错。
附报错信息：
{"level":"error","msg":"service.GetPostListFromSearch err: 400 Bad Request\n","time":"2022-06-18T00:45:30+08:00"}

**Comment by alimy** [comment]
> Zinc 用docker有点麻烦啊 这个https-http问题试了好多方法都不行，求支招啊！！！
附报错信息：
{"level":"error","msg":"service.GetPostListFromSearch err: Post "[https://110.40.139.219:4080/api/paopao-data/_search\](https://110.40.139.219:4080/api/paopao-data/_search%5C)": http: server gave HTTP response to HTTPS client\n","time":"2022-06-18T00:40:04+08:00"}

zinc使用的是哪个镜像， docker-compose.yaml中的zinc是:
```sh
%> docker run -d --name zinc --user root -v ${PWD}/data/zinc:/data -p 4080:4080 -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=admin -e DATA_PATH=/data public.ecr.aws/prabhat/zinc:latest
%> docker ps
%> docker logs zinc | grep  '^\[GIN-debug].*'
....
[GIN-debug] POST   /es/_bulk                 --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] POST   /es/:target/_bulk         --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] Listening and serving HTTP on :4080
.....
...
```

zinc启动log中可以看到`[GIN-debug] Listening and serving HTTP on :4080`。 

上面docker 启动zinc 的参数`--user root` 一定要加， 否则容器中的zinc会报没有权限创建索引数据的问题。

**Comment by 120nft** [comment]
宝塔部署文档中关于zinc的部署：https://www.rocs.me/archives/paopao_bt_install.html
```
root@VM-4-9-ubuntu:~# mkdir data
root@VM-4-9-ubuntu:~# chmod -R 777 data
root@VM-4-9-ubuntu:~# docker run -d  -v /root/data:/data -e DATA_PATH="/data" -p 4080:4080 -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=admin --name zinc public.ecr.aws/h9e2j3o7/zinc:latest
```
上文说要用这个命令，试了还是不行啊
`docker run -d --name zinc --user root -v ${PWD}/data/zinc:/data -p 4080:4080 -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=admin -e DATA_PATH=/data public.ecr.aws/prabhat/zinc:latest
`
可否直接出一个可以直接用的，这样对于zinc初学者会友好一些吧 ，到现在一直卡在zinc

**Comment by 120nft** [comment]
```
[root@VM-4-17-centos ~]# docker ps -a
CONTAINER ID   IMAGE                                COMMAND          CREATED        STATUS        PORTS                                       NAMES
823f5435bbc2   public.ecr.aws/prabhat/zinc:latest   "/go/bin/zinc"   14 hours ago   Up 14 hours   0.0.0.0:4080->4080/tcp, :::4080->4080/tcp   zinc

```

还望作者指条明路啊 就这一个问题卡了好久了

**Comment by 120nft** [comment]
[root@VM-4-17-centos paopao-ce]# docker logs zinc | grep  '^\[GIN-debug].*'
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Error loading .env file"}
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Loading system indexes..."}
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Index loaded: _index_mapping"}
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Index loaded: _index_template"}
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Index loaded: _metadata"}
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Index loaded: _users"}
{"level":"debug","time":"2022-06-20T04:18:48Z","message":"Loading indexes... from disk"}
{"level":"debug","time":"2022-06-20T04:18:49Z","message":"Index loaded: _metadata.db"}
2022/06/20 04:18:49 error loading snapshot epoch: 80: unsupportred snapshot format version: 3
{"level":"debug","time":"2022-06-20T04:18:49Z","message":"Error loading index: olympics : error opening index: existing snapshots found, but none could be loaded, exiting"}
{"level":"debug","time":"2022-06-20T04:18:49Z","message":"Error loading index: olympics.ndjson : error opening index: error getting exclusive access to diretory: unable to obtain exclusive access: open data/olympics.ndjson/bluge.pid: not a directory"}
{"level":"debug","time":"2022-06-20T04:18:49Z","message":"Loading indexes from s3..."}
{"level":"debug","time":"2022-06-20T04:18:49Z","message":"Loading indexes from minio..."}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Error loading .env file"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Loading system indexes..."}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Index loaded: _index_mapping"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Index loaded: _index_template"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Index loaded: _metadata"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Index loaded: _users"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Loading indexes... from disk"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Index loaded: _metadata.db"}
2022/06/20 04:19:22 error loading snapshot epoch: 80: unsupportred snapshot format version: 3
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Error loading index: olympics : error opening index: existing snapshots found, but none could be loaded, exiting"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Error loading index: olympics.ndjson : error opening index: error getting exclusive access to diretory: unable to obtain exclusive access: open data/olympics.ndjson/bluge.pid: not a directory"}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Loading indexes from s3..."}
{"level":"debug","time":"2022-06-20T04:19:22Z","message":"Loading indexes from minio..."}
{"level":"info","method":"POST","code":400,"took":8,"time":"2022-06-20T04:20:36Z","message":"/api/paopao-data/_search"}
{"level":"info","method":"POST","code":400,"took":3,"time":"2022-06-20T04:20:38Z","message":"/api/paopao-data/_search"}
{"level":"info","method":"POST","code":400,"took":6,"time":"2022-06-20T04:20:44Z","message":"/api/paopao-data/_search"}
{"level":"info","method":"POST","code":400,"took":2,"time":"2022-06-20T04:20:49Z","message":"/api/paopao-data/_search"}
{"level":"info","method":"POST","code":400,"took":4,"time":"2022-06-20T04:23:01Z","message":"/api/paopao-data/_search"}
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
[GIN-debug] GET    /                         --> github.com/prabhatsharma/zinc/pkg/meta/v1.GUI (4 handlers)
[GIN-debug] GET    /version                  --> github.com/prabhatsharma/zinc/pkg/meta/v1.GetVersion (4 handlers)
[GIN-debug] GET    /healthz                  --> github.com/prabhatsharma/zinc/pkg/meta/v1.GetHealthz (4 handlers)
[GIN-debug] GET    /ui/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /ui/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] POST   /api/login                --> github.com/prabhatsharma/zinc/pkg/handlers.ValidateCredentials (4 handlers)
[GIN-debug] PUT    /api/user                 --> github.com/prabhatsharma/zinc/pkg/handlers.CreateUpdateUser (5 handlers)
[GIN-debug] DELETE /api/user/:userID         --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteUser (5 handlers)
[GIN-debug] GET    /api/users                --> github.com/prabhatsharma/zinc/pkg/handlers.GetUsers (5 handlers)
[GIN-debug] PUT    /api/index                --> github.com/prabhatsharma/zinc/pkg/handlers.CreateIndex (5 handlers)
[GIN-debug] GET    /api/index                --> github.com/prabhatsharma/zinc/pkg/handlers.ListIndexes (5 handlers)
[GIN-debug] DELETE /api/index/:indexName     --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteIndex (5 handlers)
[GIN-debug] POST   /api/_bulk                --> github.com/prabhatsharma/zinc/pkg/handlers.BulkHandler (5 handlers)
[GIN-debug] POST   /api/:target/_bulk        --> github.com/prabhatsharma/zinc/pkg/handlers.BulkHandler (5 handlers)
[GIN-debug] PUT    /api/:target/document     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /api/:target/_doc         --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /api/:target/_doc/:id     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /api/:target/_search      --> github.com/prabhatsharma/zinc/pkg/handlers.SearchIndex (5 handlers)
[GIN-debug] DELETE /api/:target/_doc/:id     --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteDocument (5 handlers)
[GIN-debug] GET    /api/:target/_mapping     --> github.com/prabhatsharma/zinc/pkg/handlers.GetIndexMapping (5 handlers)
[GIN-debug] PUT    /api/:target/_mapping     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateIndexMapping (5 handlers)
[GIN-debug] GET    /es/                      --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func2 (4 handlers)
[GIN-debug] GET    /es/_license              --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func3 (4 handlers)
[GIN-debug] GET    /es/_xpack                --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func4 (4 handlers)
[GIN-debug] POST   /es/_search               --> github.com/prabhatsharma/zinc/pkg/handlers/v2.SearchIndex (5 handlers)
[GIN-debug] POST   /es/:target/_search       --> github.com/prabhatsharma/zinc/pkg/handlers/v2.SearchIndex (5 handlers)
[GIN-debug] GET    /es/_index_template       --> github.com/prabhatsharma/zinc/pkg/handlers/v2.ListIndexTemplate (5 handlers)
[GIN-debug] PUT    /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.UpdateIndexTemplate (5 handlers)
[GIN-debug] GET    /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.GetIndexTemplate (5 handlers)
[GIN-debug] HEAD   /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.GetIndexTemplate (5 handlers)
[GIN-debug] DELETE /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.DeleteIndexTemplate (5 handlers)
[GIN-debug] GET    /es/:target/_mapping      --> github.com/prabhatsharma/zinc/pkg/handlers.GetIndexMapping (5 handlers)
[GIN-debug] PUT    /es/:target/_mapping      --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateIndexMapping (5 handlers)
[GIN-debug] POST   /es/:target/_doc          --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /es/:target/_doc/:id      --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /es/:target/_create/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /es/:target/_create/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /es/:target/_update/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] DELETE /es/:target/_doc/:id      --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteDocument (5 handlers)
[GIN-debug] POST   /es/_bulk                 --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] POST   /es/:target/_bulk         --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] Listening and serving HTTP on :4080
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
[GIN-debug] GET    /                         --> github.com/prabhatsharma/zinc/pkg/meta/v1.GUI (4 handlers)
[GIN-debug] GET    /version                  --> github.com/prabhatsharma/zinc/pkg/meta/v1.GetVersion (4 handlers)
[GIN-debug] GET    /healthz                  --> github.com/prabhatsharma/zinc/pkg/meta/v1.GetHealthz (4 handlers)
[GIN-debug] GET    /ui/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /ui/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] POST   /api/login                --> github.com/prabhatsharma/zinc/pkg/handlers.ValidateCredentials (4 handlers)
[GIN-debug] PUT    /api/user                 --> github.com/prabhatsharma/zinc/pkg/handlers.CreateUpdateUser (5 handlers)
[GIN-debug] DELETE /api/user/:userID         --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteUser (5 handlers)
[GIN-debug] GET    /api/users                --> github.com/prabhatsharma/zinc/pkg/handlers.GetUsers (5 handlers)
[GIN-debug] PUT    /api/index                --> github.com/prabhatsharma/zinc/pkg/handlers.CreateIndex (5 handlers)
[GIN-debug] GET    /api/index                --> github.com/prabhatsharma/zinc/pkg/handlers.ListIndexes (5 handlers)
[GIN-debug] DELETE /api/index/:indexName     --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteIndex (5 handlers)
[GIN-debug] POST   /api/_bulk                --> github.com/prabhatsharma/zinc/pkg/handlers.BulkHandler (5 handlers)
[GIN-debug] POST   /api/:target/_bulk        --> github.com/prabhatsharma/zinc/pkg/handlers.BulkHandler (5 handlers)
[GIN-debug] PUT    /api/:target/document     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /api/:target/_doc         --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /api/:target/_doc/:id     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /api/:target/_search      --> github.com/prabhatsharma/zinc/pkg/handlers.SearchIndex (5 handlers)
[GIN-debug] DELETE /api/:target/_doc/:id     --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteDocument (5 handlers)
[GIN-debug] GET    /api/:target/_mapping     --> github.com/prabhatsharma/zinc/pkg/handlers.GetIndexMapping (5 handlers)
[GIN-debug] PUT    /api/:target/_mapping     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateIndexMapping (5 handlers)
[GIN-debug] GET    /es/                      --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func2 (4 handlers)
[GIN-debug] GET    /es/_license              --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func3 (4 handlers)
[GIN-debug] GET    /es/_xpack                --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func4 (4 handlers)
[GIN-debug] POST   /es/_search               --> github.com/prabhatsharma/zinc/pkg/handlers/v2.SearchIndex (5 handlers)
[GIN-debug] POST   /es/:target/_search       --> github.com/prabhatsharma/zinc/pkg/handlers/v2.SearchIndex (5 handlers)
[GIN-debug] GET    /es/_index_template       --> github.com/prabhatsharma/zinc/pkg/handlers/v2.ListIndexTemplate (5 handlers)
[GIN-debug] PUT    /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.UpdateIndexTemplate (5 handlers)
[GIN-debug] GET    /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.GetIndexTemplate (5 handlers)
[GIN-debug] HEAD   /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.GetIndexTemplate (5 handlers)
[GIN-debug] DELETE /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.DeleteIndexTemplate (5 handlers)
[GIN-debug] GET    /es/:target/_mapping      --> github.com/prabhatsharma/zinc/pkg/handlers.GetIndexMapping (5 handlers)
[GIN-debug] PUT    /es/:target/_mapping      --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateIndexMapping (5 handlers)
[GIN-debug] POST   /es/:target/_doc          --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /es/:target/_doc/:id      --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /es/:target/_create/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /es/:target/_create/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /es/:target/_update/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] DELETE /es/:target/_doc/:id      --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteDocument (5 handlers)
[GIN-debug] POST   /es/_bulk                 --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] POST   /es/:target/_bulk         --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] Listening and serving HTTP on :4080

**Comment by 120nft** [comment]
顺便我贴下docker-compose.yaml
`version: '3.1'

services:
  db:
    image: mysql:7.0
    restart: always
    environment:
      MYSQL_DATABASE: paopao
      MYSQL_USER: paopao
      MYSQL_PASSWORD: 6J7PDWiwmhEYN2Wb
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./scripts/paopao-mysql.sql:/docker-entrypoint-initdb.d/paopao.sql
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - 110.40.139.219::3306
    networks:
      - paopao-network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 127.0.0.1::6379
    networks:
      - paopao-network
  
  zinc:
    image: public.ecr.aws/prabhat/zinc:latest
    user: root
    restart: always
    ports:
      - 110.40.139.219::4080
    volumes:
      - ./data/:/data
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: admin
      DATA_PATH: /data
    networks:
      - paopao-network
  
  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    ports:
      - 110.40.139.219:8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=paopao
      - PMA_PASSWORD=6J7PDWiwmhEYN2Wb
    networks:
      - paopao-network

  backend:
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
      - zinc
    # modify below to reflect your custom configure
    volumes:
      - ./config.yaml.sample:/app/paopao-ce/config.yaml
      - ./data/paopao-ce/data:/app/paopao-ce/data
    ports:
      - 110.40.139.219:8008:8008
    networks:
      - paopao-network

networks:
  paopao-network:
      driver: bridge
`

**Comment by alimy** [comment]
```yaml
version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: paopao
      MYSQL_USER: paopao
      MYSQL_PASSWORD: 6J7PDWiwmhEYN2Wb
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./scripts/paopao-mysql.sql:/docker-entrypoint-initdb.d/paopao.sql
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1::3306
    networks:
      - paopao-network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6379
    networks:
      - paopao-network
  
  zinc:
    image: public.ecr.aws/prabhat/zinc:latest
    user: root
    restart: always
    ports:
      - 4080
    volumes:
      - ./data/zinc/data:/data
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: admin
      DATA_PATH: /data
    networks:
      - paopao-network
  
  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=paopao
      - PMA_PASSWORD=6J7PDWiwmhEYN2Wb
    networks:
      - paopao-network

  backend:
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
      - zinc
    # modify below to reflect your custom configure
    volumes:
      - ./config.yaml.sample:/app/paopao-ce/config.yaml
      - ./data/paopao-ce/data:/app/paopao-ce/data
    ports:
      - 8008:8008
    networks:
      - paopao-network

networks:
  paopao-network:
      driver: bridge
```
db的port不要绑定 `110.40.139.219::3306` ，这样难道不会启动不了backend吗？这里db的port绑定到`127.0.0.1::3306`是 因为默认127.0.0.1访问数据库不用去赋权外网访问(偷懒的法子)，否则就需要启动db后跑去先赋权:
```
%> docker compose exec -it db sh
%> mysql -uroot -p
mysql> grant all on *.* to 'paopao'@'%' with grant option;
```
如果容器绑定特定host，就只能通过host访问了，比如host绑定为127.0.0.1，就只能本机访问，`docker compose ps`可以查看:
```sh
%> docker compose ps
NAME                     COMMAND                  SERVICE             STATUS               PORTS
paopao-ce-backend-1      "/app/paopao-ce/paop…"   backend             running (starting)   0.0.0.0:8008->8008/tcp
paopao-ce-db-1           "docker-entrypoint.s…"   db                  running              127.0.0.1:62466->3306/tcp
paopao-ce-phpmyadmin-1   "/docker-entrypoint.…"   phpmyadmin          running              0.0.0.0:8080->80/tcp
paopao-ce-redis-1        "docker-entrypoint.s…"   redis               running              0.0.0.0:62464->6379/tcp
paopao-ce-zinc-1         "/go/bin/zinc"           zinc                running              0.0.0.0:62465->4080/tcp
```
注意了， 要偷懒， db的port绑定到`127.0.0.1::3306`就不要动了， 不要动、不要动、不要动，zinc也是同理， 绑定了host，访问时是需要带上正确host的。

**Comment by alimy** [comment]
```yaml
...
Zinc: # Zinc搜索配置
  Host: http://zinc:4080    # 如果是docker compose启动， 这里的host就是zinc，容器服务名zinc
  Index: paopao-data
  User: admin
  Password: admin
...
```

**Comment by 120nft** [comment]
可否花几分钟时间远程看看？
真的不知道咋搞…… 好几个老铁也是这个问题
