### ISSUE TITLE
希望可以修改发布的信息

### ISSUE THREAD

**Issue by eluotao** [rocboss/paopao-ce#112]
有些信息 发布的时候不是很严谨，没有严格审查，之后发现错了，没法修改，只能重新发一条，或者下面评论修正。希望提供修改的选项。

可以显示修改过  原始文本  这种就更好了

**Comment by eluotao** [comment]
可以直接用粘贴的方式 上传截图。不用一个一个选。

支持oss cos 图床设置   很方便上传图片。

**Comment by eluotao** [comment]
发布的文本 支持简单的mardown

比如序列 代码块 加粗 这三个就行。

**Comment by eluotao** [comment]
搜索内容有问题，很多都搜不到。在官方示例中搜索 也是一样的。

尝试过的关键词：BlockBeats KOOOL Gicaw4MUM

搜索需要优化 不然发布的信息 都搜不到。

**Comment by orziz** [comment]
本质上来说，泡泡是基于推特或者微博形式来做的，所以，**代码块**以及**加粗**这些，暂时不会考虑。
**重新编辑**的话，这个功能涉及一些其他问题，所以需要仔细评估。

**Comment by rocboss** [comment]
1. 泡泡动态更注重实效性，和文章不一样，所以不考虑支持”重新编辑“，甚至考虑后面对动态的”删除“操作也只在发布后的一段时间内开放
2. 图片粘贴上传这个后面倒是可以考虑，优先级不高
3. markdown短期不会考虑，即使加上，也会作为和图片、视频一样的扩展类型，不会直接在文字编辑上做过多干涉
4. 搜索这块，目前使用的是关键词匹配模式，给的这几个关键词 BlockBeats KOOOL Gicaw4MUM，第一个可以搜到，其他两个库里并没有

**Comment by Yakumo-Yukari** [comment]
> 3\. markdown

markdown 感觉不需要支持  谁会在社交平台上使用MD语法和展示啊
