### ISSUE TITLE
demo演示站无法绑定手机号

### ISSUE THREAD

**Issue by muabl** [rocboss/paopao-ce#12]
填了手机号还是提示输入手机号，并且已经获取了验证码，但是无法点击绑定

**Comment by rocboss** [comment]
感谢提醒，可以复现，应该是今天commit的东西有点问题，稍后修复

**Comment by rocboss** [comment]
@muabl 可以再试下，已经修复了

**Comment by muabl** [comment]
> @muabl 可以再试下，已经修复了

不行噢，我是手机端，手机号跟验证码那一栏都是有红色提示输入

**Comment by muabl** [comment]
好了，清除缓存
