### ISSUE TITLE
有谁搭建好的，能贴出来参观下吗？

### ISSUE THREAD

**Issue by 120nft** [rocboss/paopao-ce#124]

**Comment by 120nft** [comment]
好几个搭建的都没法解决，部署文档确定是正确的吗。请求协助也没办法指明，每次含含糊糊……

**Comment by 120nft** [comment]
满怀敬意的去搭建-测试-反馈，希望作者完善下部署文档，目前为止社群里加的几个都没搭建成功。有些人看完文档都放弃了。我想自嗨也不是你们开发这个产品的初衷吧。

**Comment by rocboss** [comment]
> 部署文档确定是正确的吗。请求协助也没办法指明，每次含含糊糊……

最新的部署命令参考README说明，关于宝塔安装的文档，里面指明了是基于0.1.0版本的教程，仅供参考，产品高速迭代期间很多配置都有可能变化，稳定后会考虑再出一份安装教程。
PaoPao面向的群体需要有一定技术基础。我看了下之前的 #110 问题，里面 @alimy 已经解答的很详细了。

> 有些人看完文档都放弃了。我想自嗨也不是你们开发这个产品的初衷吧。

PaoPao这个产品开源是为了分享，为了抛砖引玉，为了能帮助到对其有价值的用户，这就是我们的初衷。
任何有需要的人都可以免费使用PaoPao，如果你觉得这个产品不符合你需求，你也完全可以寻找其他替代品。
