### ISSUE TITLE
Go语言 新手 make run 遇到这个问题是什么原因？

### ISSUE THREAD

**Issue by MidnightDJ** [rocboss/paopao-ce#126]
`{"level":"info","msg":"github.com/rocboss/paopao-ce/internal/conf/db.go:53\n[error] failed to initialize database, got error dial tcp: lookup db on 100.65.128.2:53: no such host","time":"2022-06-22T18:10:25+08:00"}`

已经配置过 config.yaml 。。。
求解

**Comment by orziz** [comment]
数据库链接失败

**Comment by MidnightDJ** [comment]
> 数据库链接失败

这个host并不是我配置的，请问应该在哪里修改？

**Comment by orziz** [comment]
在 config.yaml 里面有 `MySQL/HOST`

**Comment by MidnightDJ** [comment]
> 非常感谢您的帮忙，现在可以运行，谢谢啦
