### ISSUE TITLE
UI布局中间栏是否需要优化下？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [rocboss/paopao-ce#19]
![屏幕截图 2022-05-30 170353](https://user-images.githubusercontent.com/12076232/170958371-3e8df438-d446-4582-a4dd-aaa91a88618d.png)

中间布局感觉太小了  问下看起来发虚  感觉很小

**Comment by orziz** [comment]
中间布局可以配置了，修改 `src/assets/css/main.less` 文件内 `:root{ --content-main: 500px; }` 的值即可，参考
Duplicate of #20
