### ISSUE TITLE
希望提供一个 Docker 安装的版本。

### ISSUE THREAD

**Issue by eluotao** [rocboss/paopao-ce#26]
Docker 安装测试 更方便些。正式版再考虑安装的主机上。

**Comment by eluotao** [comment]
如果支持Api接口发布，就更好了。可以作为一个简单的n8n 信息整合网站。

**Comment by orziz** [comment]
Docker 问题参考 #22 
另外，本身就是支持api接口发布的啊……参考借口 `post/post`

**Comment by orziz** [comment]
Docker 问题参考 #22 
另外，本身就是支持api接口发布的啊……参考接口 `post/post`
