### ISSUE TITLE
关于 user/messages 接口

### ISSUE THREAD

**Issue by orziz** [rocboss/paopao-ce#28]
此接口是获取用户的消息内容列表，但是真的有必要将 **帖子内容(`post`)** 、 **评论内容(`comment`)** 以及 **回复内容(`reply`)** 的数据一起塞进去吗？这会不会导致数据臃肿？

**Comment by rocboss** [comment]
消息列表的一次接口返回满载数据也就10k左右，而且消息列表本身也就是个相对低频的请求。
按照数据类型Hook进去的好处是，后续交互如果调整，比如说”消息预览“、“消息摘要”等，这种情况直接从现有数据里就可以读取，如果到时候再异步去load，反而会增加不必要的网络开销。

**Comment by orziz** [comment]
纯消息满载为 `(200（最大字数）*4（中文字节）*3（内容+评论+回复）*20（条数）)/1024 = 46.875 kb`，确实数据量不大。
嘛，也行。

![image](https://user-images.githubusercontent.com/36832622/171139688-2d9e853b-2644-4caa-8271-bd96229677ca.png)
