### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by Howard-guo** [rocboss/paopao-ce#50]
`go build -o paopao-api .
build github.com/rocboss/paopao-ce: cannot load embed: malformed module path "embed": missing dot in first path element
`
go version
go version go1.13.8 linux/amd64

**Comment by onenov** [comment]
我也遇到一样的问题

**Comment by alimy** [comment]
go version need go1.16+

**Comment by alimy** [comment]
//go:embed support is since go1.16
