### ISSUE TITLE
安装成功后，修改config.yaml之后

### ISSUE THREAD

**Issue by xbzu** [rocboss/paopao-ce#56]
安装过程中没有添加阿里oss和sms
安装完成后添加了阿里oss和sms
然后 go build -o paopao-api .
         chmod +x paopao-api
之后 重启了 supervisor 的进程 ，图片上传还是失败了 sms手机验证码也没有生效

请问，这里应该怎么做

谢谢回复

**Comment by xbzu** [comment]
这是我的阿里云oss配置
  AliossAccessKeyID: LTAI5tL4P95Spgju
  AliossAccessKeySecret: 06w6lDzdkePLlUBB
  AliossEndpoint: oss-cn-beijing.aliyuncs.com
  AliossBucket: uukccc
  AliossDomain: uukccc.oss-cn-beijing.aliyuncs.com

这是sms配置
  SmsJuheKey: bbf1e913224e1e05b5b
  SmsJuheTplID: JH7c8dbbf900df3f39032e97cc3

**Comment by xbzu** [comment]
阿里云和sms的设置是程序整个安装完之后进config.yaml修改的

**Comment by rocboss** [comment]
> 这是我的阿里云oss配置 AliossAccessKeyID: LTAI5tL4P95Spgju AliossAccessKeySecret: 06w6lDzdkePLlUBB AliossEndpoint: oss-cn-beijing.aliyuncs.com AliossBucket: uukccc AliossDomain: uukccc.oss-cn-beijing.aliyuncs.com
> 
> 这是sms配置 SmsJuheKey: bbf1e913224e1e05b5b SmsJuheTplID: JH7c8dbbf900df3f39032e97cc3

1. OSS配置不对，去zinc里查看日志(paopao-log)，报：bucket.PutObject err: oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage=\"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.\"
2. SMS配置不对，SmsJuheKey 是32位，SmsJuheTplID 是数字
