### ISSUE TITLE
请问输入话题后  在编辑框里不会像推特那样高亮是故意这么设计的吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [rocboss/paopao-ce#7]
![20220527200943](https://user-images.githubusercontent.com/12076232/170696818-640b82fc-121a-4f6a-a09f-411f1dcb6240.png)
![20220527201016](https://user-images.githubusercontent.com/12076232/170696831-6f5d5642-eca2-443c-8e4a-f770969835ed.png)

**Comment by rocboss** [comment]
倒不是特意这么设计的，这块用的naive-ui现有的mention组件，没有做定制，后面有时间可以再精细化一些。
另外你这个截图里"发布"按钮颜色怎么这个样子，是改过了吗？

**Comment by Yakumo-Yukari** [comment]
> 倒不是特意这么设计的，这块用的naive-ui现有的mention组件，没有做定制，后面有时间可以再精细化一些。 另外你这个截图里"发布"按钮颜色怎么这个样子，是改过了吗？


哦 原来如此  蓝色按钮我在直接在你网站上改了下颜色 想看看 如果是蓝色效果怎么样
