### ISSUE TITLE
希望热门标签增加自定义图标

### ISSUE THREAD

**Issue by emengweb** [rocboss/paopao-ce#77]
建议可以增加设置，对特定的热门话题指定图标
类似于这样：
![image](https://user-images.githubusercontent.com/31469739/172984343-fa78516b-5089-4798-ac7f-30ff08c9ee76.png)

**Comment by rocboss** [comment]
目前话题完全由用户贡献，从发布文字中提取，本身是缺乏图标属性的。后面针对优质话题，会考虑由官方提取出推荐话题，同时扩展补充这部分信息
