### ISSUE TITLE
添加文章可见性功能

### ISSUE THREAD

**Issue by alimy** [rocboss/paopao-ce#93]
* 发表文章时，可以设置文章的可见性: 公开、私有 (或者 好友可见, 好友功能或许以后可以添加)
* api需要支持文章可见性支持，包括发文章、查询广场文章列表，查询个人文章列表；
* web ui需要支持发表文章时 设置可见性：公开、私有， 默认公开；

**Comment by orziz** [comment]
good

**Comment by rocboss** [comment]
比较实用的功能，支持
